### ISSUE TITLE
error when bot dies

### ISSUE THREAD

**Issue by ya4ept** [alisonrag/NodeKore#3]
```
[socket] TCP server listening on {"address":"127.0.0.1","family":"IPv4","port":1234}
[discord] Logged in as NKore#4496!
[socket] New client connected: 127.0.0.1:64481   ID: 0
[socket] Received BOT_BASE_LEVEL_CHANGED from 106324:eee3
t:\GIT\NodeKore\src\app.js:189
                this.client.channels.cache.get(this.channelID).send(message);
                                                              ^

TypeError: Cannot read property 'send' of undefined
    at App.sendDiscordMessage (NodeKore\src\app.js:189:49)
    at Socket.<anonymous> (NodeKore\src\app.js:154:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by alisonrag** [comment]
did u configured the BOT_CHANNEL in config.json?
https://github.com/alisonrag/NodeKore/blob/5cd0520171cfa3b9e56e81ed7445e70096928d38/conf/config.json#L8

**Comment by alisonrag** [comment]
try this:
https://github.com/alisonrag/NodeKore/commit/2d457526707839f595a49635ce30a42c17d9e244

use !channel command to define the channel id

**Comment by ya4ept** [comment]
the last update solved the problems, thanks:
![изображение](https://user-images.githubusercontent.com/7117363/103284951-c10f1500-49ed-11eb-9ae9-1cab4fbf4b71.png)
